apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrabbitfortanzus.example.crossplane.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: XRabbitForTanzu
  resources:
    - name: rabbitinstance 
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: rabbitmq.com/v1beta1
              kind: RabbitmqCluster
              metadata:
                namespace: default
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
        