apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbrokerfortanzujets.carto.crossplane.io
spec:
  compositeTypeRef:
    apiVersion: carto.crossplane.io/v1alpha1
    kind: XBrokerForTanzuJet
  resources:
    - base:
        apiVersion: mq.aws.jet.crossplane.io/v1alpha1 # Uncomment to use jet
        kind: Broker
        spec:
          deletionPolicy: "Delete"
          forProvider:
            brokerName: test-broker # uncomment this is using jet provider
            autoMinorVersionUpgrade: true
            engineType: RabbitMQ
            engineVersion: "3.9.13"
            deploymentMode: SINGLE_INSTANCE
            hostInstanceType: mq.m5.large
            publiclyAccessible: true
            securityGroups: []
            subnetIDs: []
            region: us-west-2
            # Uncoment users section if using jet provider
            users:
              - username: rabbit1
                passwordSecretRef:
                  key: rabbit
                  name: cloud-creds
                  namespace: upbound-system
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        #- fromFieldPath: spec.id
        #  toFieldPath: spec.id
        #- fromFieldPath: spec.id
        #  toFieldPath: spec.forProvider.brokerName
        #  transforms:
        #    - type: string
        #      string:
        #        fmt: "%s-broker"
        
