apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbrokertanzus.carto.crossplane.io
spec:
  compositeTypeRef:
    apiVersion: carto.crossplane.io/v1alpha1
    kind: XBrokerTanzu
  resources:
    - base:
        apiVersion: mq.aws.jet.crossplane.io/v1alpha2 # Uncomment to use jet
        kind: Broker
        spec:
          deletionPolicy: "Delete"
          forProvider:
            autoMinorVersionUpgrade: true
            engineType: RabbitMQ
            engineVersion: "3.9.13"
            deploymentMode: SINGLE_INSTANCE
            hostInstanceType: mq.t3.micro
            publiclyAccessible: true
            region: us-west-2
            user:
              - passwordSecretRef:
                  key: rabbit
      name: broker-for-tanzu
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.id
          toFieldPath: spec.id
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.brokerName
          transforms:
            - type: string
              string:
                fmt: "%s-broker"
        - fromFieldPath: spec.rabbitUser
          toFieldPath: spec.forProvider.user[0].username
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.user[0].passwordSecretRef.name
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.forProvider.user[0].passwordSecretRef.namespace
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              type: Opaque
          providerConfigRef:
            name: kubernetes-provider
      name: secret-for-rabbit-tanzu
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.manifest.metadata.name
        - fromFieldPath: spec.rabbitSecret
          toFieldPath: spec.forProvider.manifest.data[rabbit]
        - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.forProvider.manifest.metadata.namespace