apiVersion: example.crossplane.io/v1alpha1
kind: RabbitForTanzu
metadata:
  creationTimestamp: "2022-03-24T00:37:07Z"
  finalizers:
  - finalizer.apiextensions.crossplane.io
  generation: 3
  labels:
    carto.run/run-template-name: crossplane-runner
    carto.run/runnable-name: crossplane-runnable
  name: rmq-runnable
  namespace: default
  ownerReferences:
  - apiVersion: carto.run/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Runnable
    name: crossplane-runnable
    uid: 9a8a0bf7-3909-4621-832c-581833b6458c
  resourceVersion: "3229551"
  uid: 715b45e6-6589-4f29-9a9f-d10ce5c75fbc
spec:
  compositionRef:
    name: xrabbitfortanzus.example.crossplane.io
  compositionUpdatePolicy: Automatic
  part-of: spring-sensors
  resourceRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: XRabbitForTanzu
    name: rmq-runnable-gx5fm
status:
  conditions:
  - lastTransitionTime: "2022-03-24T00:37:08Z"
    reason: Available
    status: "True"
    type: Ready
