apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: upbound-runner
spec:
  #outputs:
  #  binding: .status.binding[?(@.name=="name")].value
  template:
    apiVersion: carto.crossplane.io/v1alpha1
    kind: BrokerTanzu
    metadata:
      generateName: upbound-runner-
    spec:
      id: $(runnable.spec.inputs.infra-id)$
      rabbitUser: $(runnable.spec.inputs.rabbitUser)$
      rabbitSecret: $(runnable.spec.inputs.rabbitSecret)$
      part-of: $(runnable.spec.inputs.part-of)$
      writeConnectionSecretToRef:
        name: $(workload.metadata.name)$-connection