apiVersion: v1
items:
- apiVersion: carto.run/v1alpha1
  kind: ClusterSupplyChain
  metadata:
    name: crossplanetest-mr-only
  spec:
    resources:
    - name: infra
      templateRef:
        kind: ClusterTemplate
        name: crossplane-template-mr-only
    selector:
      apps.tanzu.vmware.com/workload-type: crossplanetest-mr-only
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
