apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: upbound-tanzu
spec:
  params:
    - name: infra-id
      default: $(workload.metadata.name)$
    - name: rabbitUser
      default: rabbit1
    - name: rabbitSecret
      default: none
  selector:
    apps.tanzu.vmware.com/workload-type: cloud
  resources:
    - name: infra
      templateRef:
        kind: ClusterTemplate
        name: upbound-runner