apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: crossplane-runner
spec:
  #outputs:
  #  binding: .status.binding[?(@.name=="name")].value
  template:
    apiVersion: carto.crossplane.io/v1alpha1
    kind: BrokerTanzu
    metadata:
      name: rmq-runnable
    spec:
      part-of: spring-sensors