apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: crossplane-runner
spec:
  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(workload.metadata.name)$
    spec:
      serviceAccountName: default
      runTemplateRef:
        name: crossplane-runner