apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: upbound-tanzu
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: cloud
  resources:
    - name: infra
      templateRef:
        kind: ClusterTemplate
        name: upbound-runner