apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: upbound-runner
spec:
  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(params.infra-id)$
    spec:
      serviceAccountName: default
      runTemplateRef:
        name: upbound-runner
      inputs:
        #infra-id: $(params.infra-id)$
        rabbitUser: $(params.rabbitUser)$
        rabbitSecret: $(params.rabbitSecret)$
        part-of: $(workload.metadata.labels.part-of)$