apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: crossplane-runnable
  labels:
    apps.tanzu.vmware.com/workload-type: crossplanetest-runnable
spec:
  source:
    git:
      url: https://github.com/ryan-a-baker/spring-sensors-rabbit.git
      ref:
        branch: main