apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: rmq-mr1
spec:
  forProvider:
    manifest:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      metadata:
        namespace: default
  providerConfigRef:
    name: kubernetes-provider
  #managementPolicy:
  #  type: ObserveDelete