apiVersion: tap.upbound.io/v1alpha1
kind: AwsBrokerMq
metadata:
  name: spring-sensors
spec:
  id: spring-sensors
  region: us-west-2
  engineVersion: "3.9.13"
  publishConnectionDetailsTo:
    name: spring-sensors-connection
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: spring-sensors