apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: upbound-runner
spec:
  #outputs:
  #  binding: .status.binding[?(@.name=="name")].value
  template:
    apiVersion: tap.upbound.io/v1alpha1
    kind: AwsBrokerMq
    metadata:
      #generateName: $(runnable.spec.inputs.infra-id)$-
      name: $(runnable.spec.inputs.infra-id)$
    spec:
      id: $(runnable.spec.inputs.infra-id)$
      region: $(runnable.spec.inputs.region)$
      engineVersion: $(runnable.spec.inputs.engineVersion)$
      #part-of: $(runnable.spec.inputs.part-of)$
      publishConnectionDetailsTo:
        name: $(runnable.spec.inputs.infra-id)$-connection
        metadata:
          labels: 
            services.apps.tanzu.vmware.com/class: $(runnable.spec.inputs.infra-id)$